name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build SmartcarMqttController
      - working-on ./android
        run: gradlew build --stacktrace

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for SmartcarMqttController
      - working-on: ./android
        run: gradlew test --info

  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run instrumented tests for SmartcarMqttController
      - working-on: ./android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: gradlew connectedAndroidTest