name: Android CI

on: [push, pull_request]

defaults:
  run:
    working-directory: android

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build SmartcarMqttController
        run: |
          ./gradlew build --stacktrace

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for SmartcarMqttController
        run: |
          ./gradlew test --info

  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run instrumented tests for SmartcarMqttController
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest